#
#SqlDatasource connection properties
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: hbstudent
    password: hbstudent
  main:
    banner-mode: off

#
#Hikari Configuration Properties
#
  hikari:
    connectionTimeout:
    idleTimeout:
    maxLifetime:
    maximum-pool-size:

