spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-ui
      enabled: true


  main:
    banner-mode: off